_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone" 
    DEPTH: "269x"  
    WITH_IBN: True
    NORM : "syncBN"
  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")
    CE:
      EPSILON: 0.0  
  HEADS:
    NECK_FEAT: "after"
    CLS_LAYER: "circleSoftmax" 
    POOL_LAYER: "gempool"
    SCALE: 64
    MARGIN: 0.35 
TEST:
  IMS_PER_BATCH: 512
  EVAL_PERIOD: 60
  RERANK:
    ENABLED: True
    K1: 27
    K2: 4
    LAMBDA: 0.8
  AQE:
    ENABLED: True
    QE_K: 5
SOLVER:
  OPT: "Adam"
  MAX_ITER: 60
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64
  AMP_ENABLED: True

  SCHED: "WarmupCosineAnnealingLR"
  DELAY_ITERS: 30
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 30
DATASETS:
  NAMES:   ("NAIC_test",) # A榜 NAIC_All  B榜测试 NAIC_test
  TESTS: ("NAIC_test",)

INPUT:
  SIZE_TRAIN: [384, 192]
  SIZE_TEST: [384, 192]
  DO_AUGMIX: True
OUTPUT_DIR: "logs/NAIC_All/B/0_269x_rcs_augmix"
